### PR TITLE
Fixes #314

### LINKED ISSUE #314: Weird focus style on Answer delete button.
### Expected behaviour
Focus style should align with other focus styles across the Author application.

### Actual behaviour
Weird shaped focus box is observed.

### Steps to reproduce the behaviour
Focus on the delete answer button.

### Technical information
Observed on fresh checkout of `master`.

#### Browser
Chrome 64.0.3282.186 (Official Build) (64-bit)

#### Operating System
Mac OSX

### Screenshot
image

### PR DESCRIPTION
**Pull request by SamGodwin2**
### What is the context of this PR?
Fixed the weird overlapping focus style on the delete answer button.
37143315-b820e42e-22b2-11e8-83c0-6519ccbf405d

### How to review 
Focus should look correct and all tests should pass.
screen shot 2018-03-19 at 10 35 48

### CODE REVIEW

File: src/components/AnswerEditor/index.js [hunk 1]
```diff
@@ -26,9 +26,9 @@ import TextAreaAnswer from "components/Answers/TextAreaAnswer";
 export const AnswerDeleteButton = styled(DeleteButton)`
   position: absolute;
   right: 0.33em;
-  top: 0.33em;
+  top: 0.2em;
   width: 1em;
-  height: 1em;
+  height: 1.3em;
   line-height: 1;
```
Comment (samiwel) [inline src/components/AnswerEditor/index.js]: Not sure about the change to `top` value here. I think removing `height` and `line-height` attributes will fix the weird focus style.

Probably better to remove these as I think it's generally better not to use fixed height. @hamishtaplin can probably confirm this.

Comment (SamGodwin2) [reply src/components/AnswerEditor/index.js]: Yep that's a better solution, ta.

Comment (hamishtaplin) [reply src/components/AnswerEditor/index.js]: Using `height` is fine for things like this as it doesn't really have any child elements.

I'd prefer the button to be square though. Just adding `overflow: hidden` instead of these changes fixes the problem.
