### PR TITLE
Fixed table column widths

### LINKED ISSUE #347: Created By field wraps awkwardly for all but the shortest of names
### Expected behaviour

Names are truncated if especially long

### Actual behaviour

Names wrap awkwardly

### Steps to reproduce the behaviour

Sign in as a user with a long name, created quesitonnaire, view on listing page

### Technical information

N/A

#### Browser

N/A

#### Operating System

N/A

### Screenshot

image

### PR DESCRIPTION
**Pull request by WickyNilliams**
### What is the context of this PR?
The Questionnaires listing previoulsy had flexible columns, and we didn't truncate text in the Created By column. This meant that usernames could awkwardly wrap, as seen below

### How to review 
* Code looks good
* Tests pass
* Table handles long title and long user names
* Check truncation works correctly throughout app (since there is now a single component for this purpose)

**Before**

image

**After**

image

**TODO**

- [x] work out why truncation is broken for MovePageModal

Fixes #347

### CODE REVIEW

**Comment by WickyNilliams** [comment]
I need to work out why truncation is no longer working in the MovePageModal before this can be merged (though the problem seems to be in master too, so maybe not worth holding this up over it)

File: src/components/Header/index.js [hunk 1]
```diff
@@ -41,16 +42,14 @@ const QuestionnaireTitle = styled.div`
   white-space: pre;
 `;
 
-const Title = styled.h1`
+const TruncatedTitle = Truncated.withComponent("h1");
+const Title = styled(TruncatedTitle)`
```
Comment (samiwel) [inline src/components/Header/index.js]: Couldn't this just become:

```javascript
const Title = Truncated.withComponent("h1")`
  font-size: 1em;
  font-weight: 600;	  font-weight: 600;
  margin: 0 2em;	  margin: 0 2em;
  width: 100%;	  width: 100%;
  text-align: center;	  text-align: center;
  line-height: 1;	  line-height: 1;
`
```
