### PR TITLE
375 eq author 288 non existent survey link doesnt re direct to a 404 error issue

### LINKED ISSUE #288: Non existent survey link doesn't re-direct to a 404 error.
### Expected behaviour
If you try to enter the url of a questionnaire page that doesn't exist using the Mock API you should be redirected to a 404 error.   

### Actual behaviour
Instead the page never loads and if you delete the mockDataStore then reload the page you get a "TypeError: Cannot read property 'sections' of null"

### Steps to reproduce the behaviour
Create a new survey, change the url to something like /#/questionnaire/1/design/5/3, the page wont load, so if you delete the mockDataStore then reload the page you sent sent to the sign in page which when you press the button returns you to the faulty url and shows the "TypeError: Cannot read property 'sections' of null".

### Technical information
Using Mock API, disabled Auth.
#### Browser
Chrome 
### Screenshot
image

### PR DESCRIPTION
**Pull request by SamGodwin2**
### What is the context of this PR?
Fixes #288 by redirecting to a 404 error if the url tries to point towards a non-existent questionnaire, section or page.  

### How to review 
Program should pass all tests and if a url is entered in the format http://localhost:3000/#/questionnaire/(random_characters)/design/58/94 you should be redirected to a 404 error rather than the program crashing

### CODE REVIEW

File: src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js [hunk 1]
```diff
@@ -38,7 +39,10 @@ export class QuestionnaireDesignPage extends Component {
   };
 
   shouldComponentUpdate(nextProps) {
-    return !isNil(nextProps.section) && !isNil(nextProps.page);
+    return (
+      (!isNil(nextProps.section) && !isNil(nextProps.page)) ||
```
Comment (samiwel) [inline src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js]: Might be worth checking to see if this can be simplified to:

File: src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js [hunk 2]
```diff
@@ -73,6 +77,14 @@ export class QuestionnaireDesignPage extends Component {
       return null;
     }
 
+    if (
+      questionnaire === undefined ||
```
Comment (samiwel) [inline src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js]:
```import { some, isNil } from "lodash"

File: src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.test.js [hunk 3]
```diff
@@ -27,12 +31,14 @@ describe("QuestionnaireDesignPage", () => {
     pages: [page]
   };
 
-  const questionnaire = {
+  let questionnaire = {
```
Comment (samiwel) [inline src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.test.js]: This can be `const` since we're not re-assigning.

**Comment by SamGodwin2** [comment]
[eq-author: #288 - Non existent survey link doesn't re-direct to a 404 error. (Issue)](https://trello.com/c/8s6ohW35/375-eq-author-288-non-existent-survey-link-doesnt-re-direct-to-a-404-error-issue)

File: src/components/NavigationSidebar/SectionNavItem.js [hunk 4]
```diff
@@ -22,6 +22,8 @@ export const AddPageBtn = styled.button`
   color: ${textInverted};
   font-weight: bold;
   font-size: 0.75em;
+  margin-bottom: 0.35em;
```
Comment (samiwel) [inline src/components/NavigationSidebar/SectionNavItem.js]: I think this change relates to another PR?

File: src/containers/enhancers/withQuestionnaire.js [hunk 5]
```diff
@@ -18,9 +20,10 @@ export const mapResultsToProps = ({ data, ownProps }) => {
     };
   }
 
-  const section = findById(questionnaire.sections, sectionId);
-  const page = findById(get(section, "pages"), pageId);
-
+  if (questionnaire !== undefined) {
+    section = findById(questionnaire.sections, sectionId);
```
Comment (WickyNilliams) [inline src/containers/enhancers/withQuestionnaire.js]: Could you remove the if statement if you changed this line to:
